<h1>Login</h1>
<br/>
<?php if($this->error):   ?>
    <p>Usuário ou senha inválidos</p>
    <?php endif; ?>
<?php
    $form = $this->form;

    $form->setAttribute('action',$this->url('livraria-admin-auth'));

    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('email'));
    echo $this->formRow($form->get('password'));

    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();