<h1>Categorias</h1>
<br>
<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller' => 'categorias', 'action' => 'new'))     ; ?>">Novo</a>
</p>
<table class="table table-bordered">
    <tr>
        <th>Nome</th>
    </tr>
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getNome(); ?>
            <a href="<?php echo $this->url('livraria-admin-interna',array('controller' => 'categorias', 'action' => 'edit', 'id' => $entity->getId())); ?>">Editar</a>
            <a href="<?php echo $this->url('livraria-admin-interna',array('controller' => 'categorias', 'action' => 'delete', 'id' => $entity->getId())); ?>">Deletar</a>

    </tr>
    <?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>